- name: Pre-configure
  hosts: workshop-instances
  vars:
      - ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Get hostname
      command: hostname
      register: hostname

    - name: Include hostname in etc hosts
      become: yes
      become_user: root
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1 localhost {{ hostname.stdout }}'

    # Set the ubuntu password to gcc2017training
    - name: Set the ubuntu user password
      user:
        name: ubuntu
        password: '$1$fiuynbkd$M7Wo.BhNSMJuN0TJruOkE/'
      become: yes
      become_user: root

    - name: Change the /etc/ssh/sshd_config file to allow password logins.
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        line: 'PasswordAuthentication yes'
      become: yes
      become_user: root

    - name: restart sshd
      service: name=sshd state=restarted
      become: yes
      become_user: root

    - name: Install Oracle java ppa
      apt_repository: repo="{{ item }}" state=present
      become: yes
      become_user: root
      with_items:
        - ppa:webupd8team/java

    - name: Update repos
      apt: update_cache=yes
      become: yes
      become_user: root

    - name: Install system packages
      become: yes
      apt: name="{{ item }}" state=latest
      with_items:
        - build-essential
        - git
        - nano
        - vim
        - emacs
        - libssl-dev
        - python2.7
        - virtualenv
        - python-pip
        - sendmail
        - proftpd-basic
        - postgresql
        - zlib1g-dev
        - dstat

    - name: Install Ansible
      pip:
        name: ansible
        version: 2.2.3

    - name: Accept Java 8 License
      become: yes
      debconf:
        name: 'oracle-java8-installer'
        question: 'shared/accepted-oracle-license-v1-1'
        value: 'true'
        vtype: 'select'

    - name: Install Oracle Java 8
      become: yes
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default

    - name: Update vimrc
      become: yes
      lineinfile:
        dest: /etc/vim/vimrc
        regexp: '"set background=dark'
        line: 'set background=dark'
