- name: Pre-configure

  hosts: workshop-instances
  
  vars:
    #ansible_user: galaxyguest
    #ansible_ssh_pass: 
    ansible_sudo_pass: <password>
  tasks:
    
    #passwordless sudo!
#    - name: Give galaxyguest and other sudoers no password sudo
#      replace: dest="/etc/sudoers" regexp="\%sudo   ALL=(ALL\:ALL) ALL" replace="%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"
#      become: yes
#      become_user: root
    
    #Oracle Java and the Atom repo
    - name: Install oracle java ppd
      apt_repository: repo="{{ item }}" state=present
      become: yes
      become_user: root
      with_items:
        - ppa:webupd8team/atom
        - ppa:webupd8team/java
      
    - name: Update repos
      apt: update_cache=yes
      become: yes
      become_user: root
      
    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      become: yes
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default
        
    - name: Install other packages
      become: yes
      apt: name="{{ item }}" state=latest
      with_items:
        - sendmail
        - proftpd-basic
        - atom
  
    - name: Install planemo
      become: yes
      pip: name="{{ item }}"
      with_items:
        - planemo
    
    - name: add port 443 to sshd
      become: yes
      lineinfile: dest=/etc/ssh/sshd_config line="Port 443" insertafter="^Port 22" state=present
      
    - name: restart sshd service
      service: name=ssh state=restarted
      become: yes
        
